{
 "title": "Мониторинг МедОрганизации",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Уровень нагрузки на оборудование",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH DeviceTypes AS (\r\n  SELECT 0 AS \"TypeId\", 'УЗИ' AS \"EquipmentType\"\r\n  UNION ALL\r\n  SELECT 1, 'КТ'\r\n  UNION ALL\r\n  SELECT 2, 'МРТ'\r\n  UNION ALL\r\n  SELECT 3, 'Рентген'\r\n  UNION ALL\r\n  SELECT 4, 'Эндоскоп'\r\n)\r\n\r\nSELECT\r\n  D.\"ModelName\" || ' (' || DT.\"EquipmentType\" || ')' AS \"Device\",\r\n  SR.\"LoadPercentage\"\r\nFROM\r\n  public.\"SimulationResults\" SR\r\n  JOIN public.\"Devices\" D ON SR.\"DeviceId\" = D.\"Id\"\r\n  JOIN DeviceTypes DT ON D.\"Type\" = DT.\"TypeId\"\r\nWHERE\r\n  SR.\"SimulationDate\" = (SELECT MAX(\"SimulationDate\") FROM public.\"SimulationResults\")\r\n"
    }
   ]
  },
  {
   "title": "Рекомендации по закупке оборудования",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH DeviceTypes AS (\r\n  SELECT 0 AS \"TypeId\", 'УЗИ' AS \"Тип оборудования\"\r\n  UNION ALL\r\n  SELECT 1, 'КТ' AS \"Тип оборудования\"\r\n  UNION ALL\r\n  SELECT 2, 'МРТ' AS \"Тип оборудования\"\r\n  UNION ALL\r\n  SELECT 3, 'Рентген' AS \"Тип оборудования\"\r\n  UNION ALL\r\n  SELECT 4, 'Эндоскоп' AS \"Тип оборудования\"\r\n),\r\nEquipmentNeeds AS (\r\n  SELECT\r\n    DT.\"Тип оборудования\",\r\n    CEIL(SUM(SR.\"LoadPercentage\") / 80.0) - COUNT(DISTINCT D.\"Id\") AS \"Необходимо докупить\"\r\n  FROM\r\n    public.\"SimulationResults\" SR\r\n    JOIN public.\"Devices\" D ON SR.\"DeviceId\" = D.\"Id\"\r\n    JOIN DeviceTypes DT ON D.\"Type\" = DT.\"TypeId\"\r\n  WHERE\r\n    SR.\"SimulationDate\" = (\r\n      SELECT MAX(\"SimulationDate\") FROM public.\"SimulationResults\"\r\n    )\r\n  GROUP BY\r\n    DT.\"Тип оборудования\"\r\n)\r\nSELECT\r\n  \"Тип оборудования\",\r\n  \"Необходимо докупить\"\r\nFROM\r\n  EquipmentNeeds\r\nWHERE\r\n  \"Необходимо докупить\" > 0\r\nORDER BY\r\n  \"Необходимо докупить\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Прогнозируемая нагрузка на оборудование по дням",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  EL.\"Date\" AS \"Дата\",\r\n    CASE\r\n    WHEN \"DeviceType\" = 0 THEN 'УЗИ'\r\n    WHEN \"DeviceType\" = 1 THEN 'КТ'\r\n    WHEN \"DeviceType\" = 2 THEN 'МРТ'\r\n    WHEN \"DeviceType\" = 3 THEN 'Рентген'\r\n    WHEN \"DeviceType\" = 4 THEN 'Эндоскоп'\r\n  END AS \"Тип оборудования\",\r\n  EL.\"LoadPercentage\" AS \"Прогнозируемая нагрузка (%)\",\r\n  EL.\"IsOverloaded\" AS \"Перегружено\"\r\nFROM\r\n  public.\"EquipmentLoadForecasts\" EL\r\nWHERE\r\n  EL.\"GeneratedDate\" = (\r\n    SELECT MAX(\"GeneratedDate\") FROM public.\"EquipmentLoadForecasts\"\r\n  )\r\nORDER BY\r\n  EL.\"DeviceType\",\r\n  EL.\"Date\" ASC;\r\n"
    }
   ]
  },
  {
   "title": "Общее количество пациентов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_TRUNC('day', \"ResearchDate\") AS \"time\",\r\n  COUNT(*) AS \"StudiesPerDay\"\r\nFROM\r\n  public.\"ResearchHistories\"\r\nGROUP BY\r\n  \"time\"\r\nORDER BY\r\n  \"time\" ASC\r\n"
    }
   ]
  },
  {
   "title": "Среднее время работы оборудования в день",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  D.\"ModelName\" AS \"Device\",\r\n  AVG(DailyUsage.\"TotalUsageMinutes\") AS \"AverageDailyUsageMinutes\"\r\nFROM\r\n(\r\n  SELECT\r\n    RH.\"DeviceId\",\r\n    DATE_TRUNC('day', RH.\"StartTime\") AS \"UsageDate\",\r\n    SUM(EXTRACT(EPOCH FROM (RH.\"EndTime\" - RH.\"StartTime\")) / 60) AS \"TotalUsageMinutes\"\r\n  FROM\r\n    public.\"ResearchHistories\" RH\r\n  WHERE\r\n    RH.\"StartTime\" IS NOT NULL\r\n    AND RH.\"EndTime\" IS NOT NULL\r\n    AND $__timeFilter(RH.\"StartTime\")\r\n  GROUP BY\r\n    RH.\"DeviceId\",\r\n    \"UsageDate\"\r\n) AS DailyUsage\r\nJOIN public.\"Devices\" D ON DailyUsage.\"DeviceId\" = D.\"Id\"\r\nGROUP BY\r\n  D.\"ModelName\"\r\nORDER BY\r\n  \"AverageDailyUsageMinutes\" DESC\r\n"
    }
   ]
  },
  {
   "title": "Среднее время ремонта оборудования",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  D.\"ModelName\" AS \"Device\",\r\n  AVG(EXTRACT(EPOCH FROM (SH.\"EndTime\" - SH.\"StartTime\"))/3600) AS \"AverageRepairTimeHours\"\r\nFROM\r\n  public.\"ServiceHistories\" SH\r\n  JOIN public.\"Devices\" D ON SH.\"DeviceId\" = D.\"Id\"\r\nWHERE\r\n  SH.\"WorkType\" = 0 -- Только ремонты (предполагая, что 0 соответствует ремонту)\r\n  AND SH.\"StartTime\" IS NOT NULL\r\n  AND SH.\"EndTime\" IS NOT NULL\r\n  AND $__timeFilter(SH.\"ServiceDate\")\r\nGROUP BY\r\n  D.\"ModelName\"\r\nORDER BY\r\n  \"AverageRepairTimeHours\" DESC\r\n"
    }
   ]
  },
  {
   "title": "Наиболее популярное исследование",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  R.\"Name\" AS \"Research\",\r\n  COUNT(RH.\"Id\") AS \"ResearchCount\"\r\nFROM\r\n  public.\"ResearchHistories\" RH\r\n  JOIN public.\"Researches\" R ON RH.\"ResearchId\" = R.\"Id\"\r\nWHERE\r\n  $__timeFilter(RH.\"ResearchDate\")\r\nGROUP BY\r\n  R.\"Name\"\r\nORDER BY\r\n  \"ResearchCount\" DESC\r\n"
    }
   ]
  },
  {
   "title": "Нагрузка на типы оборудования",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DT.\"DeviceType\" AS \"EquipmentType\",\r\n  COUNT(RH.\"Id\") AS \"UsageCount\"\r\nFROM\r\n  public.\"ResearchHistories\" RH\r\n  JOIN public.\"Devices\" D ON RH.\"DeviceId\" = D.\"Id\"\r\n  JOIN (\r\n    VALUES\r\n      (0, 'УЗИ'),\r\n      (1, 'КТ'),\r\n      (2, 'МРТ'),\r\n      (3, 'Рентген'),\r\n      (4, 'Эндоскоп')\r\n  ) AS DT(\"DeviceTypeId\", \"DeviceType\") ON D.\"Type\" = DT.\"DeviceTypeId\"\r\nWHERE\r\n  $__timeFilter(RH.\"ResearchDate\")\r\nGROUP BY\r\n  DT.\"DeviceType\"\r\nORDER BY\r\n  \"UsageCount\" DESC\r\n"
    }
   ]
  },
  {
   "title": "Количество использований",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  D.\"ModelName\" AS \"Device\",\r\n  COUNT(RH.\"Id\") AS \"ResearchCount\"\r\nFROM\r\n  public.\"ResearchHistories\" RH\r\n  JOIN public.\"Devices\" D ON RH.\"DeviceId\" = D.\"Id\"\r\nWHERE\r\n  $__timeFilter(RH.\"ResearchDate\")\r\nGROUP BY\r\n  D.\"ModelName\"\r\nORDER BY\r\n  \"ResearchCount\" DESC\r\n"
    }
   ]
  },
  {
   "title": "Среднее время проведения исследования",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  R.\"Name\" AS \"Research\",\r\n  AVG(EXTRACT(EPOCH FROM (RH.\"EndTime\" - RH.\"StartTime\"))/60) AS \"AverageResearchDurationMinutes\"\r\nFROM\r\n  public.\"ResearchHistories\" RH\r\n  JOIN public.\"Researches\" R ON RH.\"ResearchId\" = R.\"Id\"\r\nWHERE\r\n  RH.\"StartTime\" IS NOT NULL\r\n  AND RH.\"EndTime\" IS NOT NULL\r\n  AND $__timeFilter(RH.\"ResearchDate\")\r\nGROUP BY\r\n  R.\"Name\"\r\nORDER BY\r\n  \"AverageResearchDurationMinutes\" DESC\r\n"
    }
   ]
  },
  {
   "title": "Количество поломок оборудования",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  D.\"ModelName\" AS \"Device\",\r\n  COUNT(SH.\"Id\") AS \"FailureCount\"\r\nFROM\r\n  public.\"ServiceHistories\" SH\r\n  JOIN public.\"Devices\" D ON SH.\"DeviceId\" = D.\"Id\"\r\nWHERE\r\n  SH.\"WorkType\" = 0 -- 0 соответствует WorkType.Repair (ремонт)\r\n  AND $__timeFilter(SH.\"ServiceDate\")\r\nGROUP BY\r\n  D.\"ModelName\"\r\nORDER BY\r\n  \"FailureCount\" DESC\r\n"
    }
   ]
  }
 ]
}