version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Monitoring
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring-network

  api:
    image: ${DOCKER_REGISTRY-}aspnetcore-api
    build:
      context: .  # Контекстом сборки становится корневая директория
      dockerfile: MedicalMonitoring/Dockerfile  # Путь к Dockerfile внутри папки MedicalMonitoring
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=my_postgres;Port=5432;Database=Monitoring;User Id=postgres;Password=postgres;"
    networks:
      - monitoring-network

  ml_service:
    build:
      context: ./patient_flow_prediction_service
      dockerfile: patient_flow_prediction_service/Dockerfile
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  postgres-data:

networks:
  monitoring-network:
    driver: bridge