version: '3.8'

services:
  # medical-monitoring:
  #   image: medical-monitoring-app
  #   build:
  #     context: .
  #     dockerfile: ./MedicalMonitoring/Dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Monitoring
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  postgres-data:
